FROM oracle/graalvm-ce:19.2.1 as graalvm
LABEL application=mn-first-rest \
      traefik.enable="true" \
      traefik.docker.network=traefik-nt \
      traefik.http.routers.mn-first-rest.rule="PathPrefix(`/mn-first-rest/`)" \
      traefik.http.routers.mn-first-rest.service="mn-first-rest" \
      traefik.http.routers.mn-first-rest.entrypoints=web \
      traefik.http.routers.mn-first-rest.middlewares="mn-first-rest" \
      traefik.http.services.mn-first-rest.loadBalancer.server.port="8080" \
      traefik.http.middlewares.mn-first-rest.stripprefix.prefixes="/mn-first-rest/"
COPY . /home/app/eureka-cliente-sample
WORKDIR /home/app/eureka-cliente-sample
COPY target/mn-first-rest-*.jar eureka-cliente-sample-RELEASE.jar
RUN chmod 755 eureka-cliente-sample-RELEASE.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "-Dfile.encoding=UTF-8", "eureka-cliente-sample-RELEASE.jar"]