micronaut:
  application:
    name: mn-first-rest
jackson:
  serializationInclusion: ALWAYS
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: true
    failOnUnknownProperties: false