micronaut:
  #server:
    #port: 8091
  application:
    name: "mn-first-rest"
endpoints:
  health:
    enabled: true
    sensitive: true
    details-visible: ANONYMOUS
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 1
    sender:
      agentHost: jaeger-collector.local
      agentPort: 5775
    reporter:
      flushInterval: 1000
      maxQueueSize: 100