micronaut:
  application:
    name: "mn-first-rest-${HOSTNAME}"
eureka:
  client:
    registration:
      enabled: true
      app-group-name: ${micronaut.application.name}-balancer
      hostname: ${HOSTNAME}
      #appname: "${HOSTNAME:mn-first-rest}"
    defaultZone: "${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka"
  instance:
    prefer-ip-address: true