micronaut:
  #server:
    #port: 8091
  application:
    name: "mn-first-rest"
endpoints:
  health:
    enabled: true
    sensitive: true
    details-visible: ANONYMOUS
tracing:
  zipkin:
    enabled: true
    sampler:
      probability: 1
    http:
      url: http://zipkin.local:9411