micronaut:
  application:
    name: "${HOSTNAME:mn-first-rest}"
eureka:
  client:
    registration:
      enabled: true
      appname: "${HOSTNAME:mn-first-rest}"
    defaultZone: "${EUREKA_SERVER:localhost}:${EUREKA_PORT:8761}/eureka"
  instance:
    prefer-ip-address: true